/* #include "axis_blobs_fusionner.h"

////////////////////////////////////////////////////////////////////////////////

const char *KernelSource = "struct __attribute__ ((packed)) doppler_signature								"
						   "							"
						   "{																				"
						   "							"
						   "	float doppler_signature[1024][2];											"
						   "							"
						   "};																				"
						   "							"
						   "struct __attribute__ ((packed)) detection_header								"
						   "							"
						   "{																				"
						   "							"
						   "	char magic_CN[4];															"
						   "							"
						   "	unsigned int scan_number;													"
						   "							"
						   "	unsigned int ramp_number;													"
						   "							"
						   "	unsigned long timestamp;													"
						   "							"
						   "	char processing_step;														"
						   "							"
						   "	char axis;																	"
						   "							"
						   "	unsigned short doppler_signature_cells;										"
						   "							"
						   "	char spare[8];																"
						   "							"
						   "};																				"
						   "							"
						   "struct __attribute__ ((packed)) single_axis_detection_data						"
						   "							"
						   "{																				"
						   "							"
						   "	float azimuth_elevation;													"
						   "							"
						   "	float distance;    															"
						   "							"
						   "	float min_azimuth_elevation;    											"
						   "							"
						   "	float max_azimuth_elevation;    											"
						   "							"
						   "	float min_distance;    														"
						   "							"
						   "	float max_distance;    														"
						   "							"
						   "	float monopulse_ratio;														"
						   "							"
						   "	struct doppler_signature doppler_signature;									"
						   "							"
						   "};																				"
						   "							"
						   "struct __attribute__ ((packed)) single_axis_detection{							"
						   "							"
						   "																				"
						   "							"
						   "	struct detection_header header;												"
						   "							"
						   "	struct single_axis_detection_data data;										"
						   "							"
						   "};																				"
						   "							"
						   "struct __attribute__ ((packed)) imu_and_gps_data								"
						   "							"
						   "{																				"
						   "							"
						   "	unsigned long time;															"
						   "							"
						   "	long latitude;																"
						   "							"
						   "	long longitude;																"
						   "							"
						   "	long altitude;																"
						   "							"
						   "	long ecef_position_x;														"
						   "							"
						   "	long ecef_position_y;														"
						   "							"
						   "	long ecef_position_z;														"
						   "							"
						   "	float yaw;																	"
						   "							"
						   "	float pitch;																"
						   "							"
						   "	float roll;																	"
						   "							"
						   "	float velocity_north;														"
						   "							"
						   "	float velocity_east;														"
						   "							"
						   "	float velocity_up;															"
						   "							"
						   "	float acceleration_x;														"
						   "							"
						   "	float acceleration_y;														"
						   "							"
						   "	float acceleration_z;														"
						   "							"
						   "};																				"
						   "							"
						   "struct __attribute__ ((packed)) merged_detection_data							"
						   "							"
						   "{																				"
						   "							"
						   "	float azimuth;																"
						   "							"
						   "	float elevation;															"
						   "							"
						   "	float distance;																"
						   "							"
						   "	float min_azimuth;															"
						   "							"
						   "	float min_elevation;														"
						   "							"
						   "	float max_elevation;														"
						   "							"
						   "	float max_azimuth;															"
						   "							"
						   "	float min_distance;															"
						   "							"
						   "	float max_distance;															"
						   "							"
						   "	float pos_axis_x;															"
						   "							"
						   "	float pos_axis_y;															"
						   "							"
						   "	float pos_axis_z;															"
						   "							"
						   "	float monopulse_ratio_az;													"
						   "							"
						   "	float monopulse_ratio_el;													"
						   "							"
						   "};																				"
						   "							"
						   "struct __attribute__ ((packed)) merged_detection								"
						   "							"
						   "{																				"
						   "							"
						   "	struct detection_header header;												"
						   "							"
						   "	struct merged_detection_data data;											"
						   "							"
						   "	struct imu_and_gps_data imu_gps;											"
						   "							"
						   "	struct doppler_signature doppler_signature_azimuth;							"
						   "							"
						   "	struct doppler_signature doppler_signature_elevation;						"
						   "							"
						   "};																				"
						   "							"
						   "__kernel void square(                                                  			"
						   "						"
						   "   __global struct single_axis_detection* azimuth,                               "
						   "         					"
						   "   __global struct single_axis_detection* elevation,                             "
						   "           				"
						   "   __global struct imu_and_gps_data* imu_gps,                                    "
						   "   						"
						   "   __global struct merged_detection* merged,                                     "
						   "  						"
						   "   const unsigned int NUM_DETECTIONS)                                       	"
						   "							"
						   "{                                                                      			"
						   "						"
						   "   int i = get_global_id(0);                                           			"
						   "						"
						   "   if(i < NUM_DETECTIONS){                                                   	"
						   "							"
						   "       merged[i].header = elevation[i].header;             						"
						   "						"
						   "       merged[i].data.azimuth = azimuth[i].data.azimuth_elevation;             	"
						   "						"
						   "       merged[i].data.elevation = elevation[i].data.azimuth_elevation;           "
						   "  						"
						   "       merged[i].data.distance = elevation[i].data.distance;             		"
						   "							"
						   "       merged[i].data.min_azimuth = azimuth[i].data.min_azimuth_elevation;       "
						   "      					"
						   "       merged[i].data.min_elevation = elevation[i].data.min_azimuth_elevation;   "
						   "          				"
						   "       merged[i].data.max_elevation = elevation[i].data.max_azimuth_elevation;   "
						   "          				"
						   "       merged[i].data.max_azimuth = azimuth[i].data.max_azimuth_elevation;       "
						   "      					"
						   "       merged[i].data.min_distance = elevation[i].data.min_distance;             "
						   "							"
						   "       merged[i].data.max_distance = elevation[i].data.max_distance;             "
						   "							"
						   "       merged[i].data.pos_axis_x = 34;             								"
						   "						"
						   "       merged[i].data.pos_axis_y = 35;             								"
						   "						"
						   "       merged[i].data.pos_axis_z = 36;             								"
						   "						"
						   "       merged[i].data.monopulse_ratio_az = azimuth[i].data.monopulse_ratio;      "
						   "       					"
						   "       merged[i].data.monopulse_ratio_el = elevation[i].data.monopulse_ratio;    "
						   "         					"
						   "       merged[i].imu_gps = imu_gps[0];             								"
						   "						"
						   "       merged[i].doppler_signature_azimuth = azimuth[i].data.doppler_signature;  "
						   "           				"
						   "       merged[i].doppler_signature_elevation = "
						   "elevation[i].data.doppler_signature;             			"
						   "	}                                                                   		"
						   "							"
						   "	if(i==0){                                                           		"
						   "							"
						   "  		printf(\"elevation[0].header.scan_number = "
						   "%i\\n\",elevation[0].header.scan_number);      			"
						   "  		printf(\"merged[0].header.scan_number = "
						   "%i\\n\",merged[0].header.scan_number);    					"
						   "  		printf(\"elevation[1].header.scan_number = "
						   "%i\\n\",elevation[1].header.scan_number);      			"
						   "  		printf(\"merged[1].header.scan_number = "
						   "%i\\n\",merged[1].header.scan_number);    					"
						   "	}                                                                   		"
						   "							"
						   "}                                                                      			"
						   "						";


*/
////////////////////////////////////////////////////////////////////////////////
